name: Typecheck

on:
  push:
    branches: [devel, stable-*]
  pull_request:
    branches: [devel, stable-*]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: make install-dev

      - name: Run type checker
        run: make typecheck
